CREATE DATABASE IF NOT EXISTS wordpress;

ALTER USER 'root'@'localhost' IDENTIFIED BY '1234';

CREATE USER IF NOT EXISTS 'danjimen'@'%' IDENTIFIED BY '1234';

GRANT ALL PRIVILEGES ON wordpress.* TO 'danjimen'@'%';

FLUSH PRIVILEGES;